import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Инструменты",
      items: [
        "instruments/overview",
        {
          type: "category",
          label: "Разработка и отладка",
          items: [
            "instruments/console-requests",
            "instruments/console-code",
            "instruments/console-reports",
            "instruments/jobs-console",
            "instruments/http-console",
            "instruments/ws-console",
            "instruments/data-compare",
          ],
        },
        {
          type: "category",
          label: "Редакторы",
          items: [
            "instruments/constants-editor",
            "instruments/json-editor",
            "instruments/html-editor",
            "instruments/skd-editor",
            "instruments/object-editor",
            "instruments/prototype-editor",
          ],
        },
        {
          type: "category",
          label: "Администрирование",
          items: [
            "instruments/group-processing",
            "instruments/delete-marked",
            "instruments/duplicates-search",
            "instruments/db-structure",
            "instruments/navigator",
            "instruments/file-manager",
            "instruments/forms-manager",
          ],
        },
        {
          type: "category",
          label: "Обмен данными",
          items: [
            "instruments/exchange-registration",
            "instruments/xml-exchange",
            "instruments/universal-exchange",
          ],
        },
        {
          type: "category",
          label: "Утилиты",
          items: [
            "instruments/object-links",
            "instruments/dynamic-list",
            "instruments/regex-builder",
            "instruments/license-info",
            "instruments/table-loader",
            "instruments/object-count",
            "instruments/value-viewer",
            "instruments/object-compare",
            "instruments/zup-query-builder",
          ],
        },
        {
          type: "category",
          label: "Библиотеки",
          items: ["instruments/serialization-lib", "instruments/connector"],
        },
      ],
    },
    {
      type: "category",
      label: "Интеграция",
      items: ["integration/bsp", "integration/subsystems"],
    },
    {
      type: "category",
      label: "API",
      items: ["api/overview", "api/debug-api"],
    },
    {
      type: "category",
      label: "Changelog",
      items: ["changelog/overview"],
    },
  ],
  contributiongSidebar: [{ type: "autogenerated", dirName: "development" }],
};

export default sidebars;
